/*

 KRISPYKREME_BKG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define KrispyKremeBkgBank 0
/* Start of tile array. */
extern unsigned char KrispyKremeBkg[];
#define KrispyKremeBkgLen 12

/* End of KRISPYKREME_BKG.H */
